server:
  port: 8084  # Support Service port

spring:
  application:
    name: support-service
  datasource:
    url: jdbc:postgresql://localhost:15432/cinema_db?currentSchema=support
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/cinema-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: cinema-realm
    client-id: support-service
    client-secret: ${KEYCLOAK_CLIENT_SECRET}