server:
  port: 8090

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        web flux:
          routes:
            - id: core-service
              uri: lb://CORE-SERVICE
              predicates:
                - Path=/core/**
            - id: discovery-service
              uri: lb://DISCOVERY-SERVICE
              predicates:
                - Path=/discovery/**

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8180/realms/cinema-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

